apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd-server.argocd.svc.cluster.local:443
  dex.config: |
    connectors:
      - name: github
        config:
          clientID: your-github-client-id
          clientSecret: your-github-client-secret
          redirectURI: https://argocd-server.argocd.svc.cluster.local:443/api/dex/callback
