apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: default
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://github.com/your-username/myapp-argocd-config.git
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
